name: 'single-variable-mapper'
description: 'Github action to simplify variable mapping by a specific key'
author: 'caseycs'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  color: green
  icon: arrow-right

# Define your inputs here.
inputs:
  key:
    description: 'Key to match the map argument'
    required: true
  map:
    description:
      'Pairs of regular expressions and resulting values, divided by separator'
    required: true
  export_to:
    description:
      'Comma-separated list of targets to export variables to. Possible optoins:
      env, output'
    default: 'output'
  export_to_env_name:
    description: 'Environment variable name when export_to contains env'
    default: ''
  separator:
    description: 'Separator between regular expression and result value'
    default: ':'
  mode:
    description:
      'Specify the behavior of getting the variable. Possible options: strict,
      fallback-to-original, fallback-to-default'
    default: 'strict'
  default:
    description:
      'Default value, used when mode is fallback-to-default and not match was
      found'
    default: ''
  allow_empty_map:
    description:
      'Do not throw error when empty map was provided, requires mode to be other
      than strict'
    default: ''

# Define your outputs here.
outputs:
  value:
    description: 'Mapped value'

runs:
  using: node20
  main: dist/index.js
