name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action 1
        id: test-action-1
        uses: ./
        with:
          key: staging-5
          map: |
            staging-\d+: staging

      - name: Test Local Action 1 - print output
        id: output
        run: set -e; [ "${{ steps.test-action-1.outputs.value }}" == "staging" ]

      - name: Test Local Action 2
        id: test-action-2
        uses: ./
        with:
          key: staging-5
          allow_empty_map: true
          mode: fallback-to-original

      - name: Test Local Action 2 - print output
        id: output
        run: set -e; [ "${{ steps.test-action-2.outputs.value }}" == "staging-5" ]
